version: "3.7"
services:
  webapp:
    environment:
      - "MONGODB_HOST=db"
    image: "${USER}/rest-example-app:1.0.0"
    ports:
      - "9292:9292"
    volumes:
      - ".:/var/app"
    depends_on:
      - "db"
  db:
    image: mongo:3.6.17-xenial
    restart: always
