version: "3.7"
services:
  webapp:
    environment:
      - "DB_HOST=localhost"
      - "TOKEN"
    image: "${USER}/rest-example-app:1.0.0"
    ports:
      - "9292:9292"
    depends_on:
      - "db"
  db:
    image: mongo:3.6.17-xenial
    restart: always
